name: Checks

on:
  pull_request:
    branches: [main] # When we create a pull request on main 
    # It will target this workflow

 
jobs:
  test-lint: # ID of the job for the system
    name: Test and Lint # User-friendly name
    uses: ./.github/workflows/test-and-lint.yml # Allows us to use this file
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }} # This is how we pull environment variables from GitHub
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # Easy to pass them into that test and lint file